name: Publish the latext image to Docker hub

on:
  push: 
    branches: 
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: selkharz/latexcompiler:latest